# CHANGEME: Set these variable to your liking
title: ESPHome Projects by <a href="https://veli.ee)/[git](https://github.com/velijv">Veli</a>
description: Powered by ESPHome and ESP Web Tools
remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
google_analytics: G-5H8W7JPJW7
