name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      #files: project-template-esp32.yaml,project-template-esp8266.yaml
      files: nspanel.yaml,switchman-m5-1c.yaml,switchman-m5-2c.yaml,switchman-m5-3c.yaml
      # CHANGEME: Set the name of your project here:
      name: NSPanel 
